/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CadastroFrames;

import Objetos.Grupo;
import Objetos.Membro;
import Util.FormatoDataHora;
import gerenciador.de.igreja.BuscaFrame;
import gerenciador.de.igreja.BuscadorDeMembro;
import gerenciador.de.igreja.GerenciadorFrame;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author elise
 */
public class FrameGrupo extends javax.swing.JFrame implements BuscadorDeMembro{

    private GerenciadorFrame gerenciador;
    private Grupo grupo;
    private List<Membro> membros;
    /**
     * Creates new form FrameTurmas
     */
    public FrameGrupo() {
        initComponents();
    }
    
    public FrameGrupo(GerenciadorFrame gerenciador, Grupo grupo) {
        initComponents();
        this.grupo = grupo;
        this.gerenciador = gerenciador;
        membros = grupo.selectMembros();
        carregarInfoGrupo();
        atualizarTabela();
    }
    
    private void carregarInfoGrupo(){
        lbLider.setText(grupo.getLider().getPessoa().getNome());
        lbTipoGrupo.setText(grupo.getTipoGrupo());
        lbDiaSemana.setText(grupo.getId().getDiaSemana());
        lbHora.setText(FormatoDataHora.userHora(grupo.getId().getHora()));
    }

    public final void atualizarTabela(){
        DefaultTableModel model = (DefaultTableModel) tabelaParticipantes.getModel();
        model.setRowCount(0);
        Object[] obj = new Object[4];
        for (Membro membro: membros){
            obj[0] = membro.getPessoa().getNome();
            obj[1] = membro.getPessoa().getSobrenome();
            obj[2] = membro.getPessoa().getEndBairro();
            obj[3] = membro.getPessoa().getEndCidade();
            model.addRow(obj);
        }
    }
       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaParticipantes = new javax.swing.JTable();
        btnFechar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbTipoGrupo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbLider = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbDiaSemana = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbHora = new javax.swing.JLabel();
        btnAlocarMembro = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnAlterarGrupo = new javax.swing.JButton();

        setTitle("Connect Church - Grupo");

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Grupo");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 625, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        tabelaParticipantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "NOME", "SOBRENOME", "BAIRRO", "CIDADE"
            }
        ));
        jScrollPane1.setViewportView(tabelaParticipantes);

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel2.setText("Participantes:");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Tipo:");

        lbTipoGrupo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        lbTipoGrupo.setText("tipo_grupo");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Líder:");

        lbLider.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbLider.setText("nome_líder");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("Dia:");

        lbDiaSemana.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbDiaSemana.setText("00/00/0000");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setText("Hora:");

        lbHora.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbHora.setText("00:00");

        btnAlocarMembro.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnAlocarMembro.setForeground(new java.awt.Color(0, 102, 102));
        btnAlocarMembro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buscar2.png"))); // NOI18N
        btnAlocarMembro.setText("Alocar Membro");
        btnAlocarMembro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlocarMembroActionPerformed(evt);
            }
        });

        btnExcluir.setBackground(new java.awt.Color(255, 204, 204));
        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/deletar.png"))); // NOI18N
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnAlterarGrupo.setText("Alterar dados");
        btnAlterarGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarGrupoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbTipoGrupo)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbLider)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbDiaSemana)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbHora)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAlterarGrupo)
                        .addGap(17, 17, 17))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAlocarMembro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lbTipoGrupo)
                    .addComponent(jLabel5)
                    .addComponent(lbLider)
                    .addComponent(jLabel7)
                    .addComponent(lbDiaSemana)
                    .addComponent(jLabel9)
                    .addComponent(lbHora)
                    .addComponent(btnAlterarGrupo))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAlocarMembro)
                        .addComponent(btnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        try {
            // TODO add your handling code here:
            this.dispose();
        } catch (Throwable ex) {
            Logger.getLogger(FrameGrupo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnAlocarMembroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlocarMembroActionPerformed
        // TODO add your handling code here:
        BuscaFrame buscarframe = new BuscaFrame(this);
        buscarframe.setVisible(true);
    }//GEN-LAST:event_btnAlocarMembroActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int index = tabelaParticipantes.getSelectedRow();
        if (index == -1){
            JOptionPane.showMessageDialog(null, "Selecione um participante para excluir");
            return;
        }
        Membro excluido = membros.get(index);
        try {
            grupo.removerMembro(excluido);
            membros.remove(index);
            atualizarTabela();
        } catch (Exception ex) {
            //Logger.getLogger(FrameGrupo.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Houve um problema ao excluir membro: "+ex.toString());
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnAlterarGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarGrupoActionPerformed
        CadFrameGrupo cadFrameGrupo = new CadFrameGrupo(gerenciador, grupo);
        cadFrameGrupo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAlterarGrupoActionPerformed

     @Override
    public void tratarMembroSelecionado(Membro membro) {
        try {
            grupo.adicionarMembro(membro);
            //método não mto eficiente.. mas que funciona
            membros = grupo.selectMembros();
            atualizarTabela();
        } catch (Exception ex) {
            //Logger.getLogger(FrameGrupo.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Houve um erro ao adicionar o membro: "+ex.toString());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlocarMembro;
    private javax.swing.JButton btnAlterarGrupo;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnFechar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbDiaSemana;
    private javax.swing.JLabel lbHora;
    private javax.swing.JLabel lbLider;
    private javax.swing.JLabel lbTipoGrupo;
    private javax.swing.JTable tabelaParticipantes;
    // End of variables declaration//GEN-END:variables
}
