package Objetos;
// Generated 03/06/2016 10:35:37 by Hibernate Tools 4.3.1

import Util.HibernateUtil;
import java.util.Date;




/**
 * Assiduidade generated by hbm2java
 */
public class Assiduidade  implements java.io.Serializable {


     private AssiduidadeId id;
     private Matricula matricula;
     private boolean presenca;

    public Assiduidade() {
        this.id = new AssiduidadeId();
    }

    public Assiduidade(Date dataAula, Matricula matricula, boolean presenca) {
       this.id = new AssiduidadeId();
       this.id.setDataAula(dataAula);
       setMatricula(matricula);
       this.presenca = presenca;
    }
   
    public AssiduidadeId getId() {
        return this.id;
    }
    
    public void setId(AssiduidadeId id) {
        this.id = id;
    }
    public Matricula getMatricula() {
        return this.matricula;
    }
    
    public final void setMatricula(Matricula matricula) {
        this.matricula = matricula;
        this.id.setCodigo(matricula.getId().getCodDisc());
        this.id.setIdAluno(matricula.getAluno().getId());
        this.id.setDataInicio(matricula.getId().getDataInicio());
    }
    
    public boolean isPresenca() {
        return this.presenca;
    }
    
    public void setPresenca(boolean presenca) {
        this.presenca = presenca;
    }

    public static void cadastrarOuAtualizarAssiduidade(Assiduidade assiduidade) throws Exception{
        HibernateUtil.persistirObjeto(assiduidade);
    }
    
    public static void deletarAssiduidade(Assiduidade assiduidade) throws Exception{
        HibernateUtil.deletarObjeto(assiduidade);
    }
}


