package Objetos;
// Generated 03/06/2016 10:35:37 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * AssiduidadeId generated by hbm2java
 */
public class AssiduidadeId  implements java.io.Serializable {


     private Date dataAula;
     private int idAluno;
     private String codigo;
     private Date dataInicio;

    public AssiduidadeId() {
    }

    public AssiduidadeId(Date dataAula, int idAluno, String codigo, Date dataInicio) {
       this.dataAula = dataAula;
       this.idAluno = idAluno;
       this.codigo = codigo;
       this.dataInicio = dataInicio;
    }
   
    public Date getDataAula() {
        return this.dataAula;
    }
    
    public void setDataAula(Date dataAula) {
        this.dataAula = dataAula;
    }
    public int getIdAluno() {
        return this.idAluno;
    }
    
    public void setIdAluno(int idAluno) {
        this.idAluno = idAluno;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public Date getDataInicio() {
        return this.dataInicio;
    }
    
    public void setDataInicio(Date dataInicio) {
        this.dataInicio = dataInicio;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AssiduidadeId) ) return false;
		 AssiduidadeId castOther = ( AssiduidadeId ) other; 
         
		 return ( (this.getDataAula()==castOther.getDataAula()) || ( this.getDataAula()!=null && castOther.getDataAula()!=null && this.getDataAula().equals(castOther.getDataAula()) ) )
 && (this.getIdAluno()==castOther.getIdAluno())
 && ( (this.getCodigo()==castOther.getCodigo()) || ( this.getCodigo()!=null && castOther.getCodigo()!=null && this.getCodigo().equals(castOther.getCodigo()) ) )
 && ( (this.getDataInicio()==castOther.getDataInicio()) || ( this.getDataInicio()!=null && castOther.getDataInicio()!=null && this.getDataInicio().equals(castOther.getDataInicio()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getDataAula() == null ? 0 : this.getDataAula().hashCode() );
         result = 37 * result + this.getIdAluno();
         result = 37 * result + ( getCodigo() == null ? 0 : this.getCodigo().hashCode() );
         result = 37 * result + ( getDataInicio() == null ? 0 : this.getDataInicio().hashCode() );
         return result;
   }   


}


