package Objetos;
// Generated 03/06/2016 10:35:37 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * MatriculaId generated by hbm2java
 */
public class MatriculaId  implements java.io.Serializable {


     private int idAluno;
     private String codDisc;
     private Date dataInicio;

    public MatriculaId() {
    }

    public MatriculaId(int idAluno, String codDisc, Date dataInicio) {
       this.idAluno = idAluno;
       this.codDisc = codDisc;
       this.dataInicio = dataInicio;
    }
   
    public int getIdAluno() {
        return this.idAluno;
    }
    
    public void setIdAluno(int idAluno) {
        this.idAluno = idAluno;
    }
    public String getCodDisc() {
        return this.codDisc;
    }
    
    public void setCodDisc(String codDisc) {
        this.codDisc = codDisc;
    }
    public Date getDataInicio() {
        return this.dataInicio;
    }
    
    public void setDataInicio(Date dataInicio) {
        this.dataInicio = dataInicio;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MatriculaId) ) return false;
		 MatriculaId castOther = ( MatriculaId ) other; 
         
		 return (this.getIdAluno()==castOther.getIdAluno())
 && ( (this.getCodDisc()==castOther.getCodDisc()) || ( this.getCodDisc()!=null && castOther.getCodDisc()!=null && this.getCodDisc().equals(castOther.getCodDisc()) ) )
 && ( (this.getDataInicio()==castOther.getDataInicio()) || ( this.getDataInicio()!=null && castOther.getDataInicio()!=null && this.getDataInicio().equals(castOther.getDataInicio()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdAluno();
         result = 37 * result + ( getCodDisc() == null ? 0 : this.getCodDisc().hashCode() );
         result = 37 * result + ( getDataInicio() == null ? 0 : this.getDataInicio().hashCode() );
         return result;
   }   


}


