package Objetos;
// Generated 03/06/2016 10:35:37 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * MinistracaoId generated by hbm2java
 */
public class MinistracaoId  implements java.io.Serializable {


     private String temaEvt;
     private Date diaHoraEvt;
     private String tituloMsg;

    public MinistracaoId() {
    }

    public MinistracaoId(String temaEvt, Date diaHoraEvt, String tituloMsg) {
       this.temaEvt = temaEvt;
       this.diaHoraEvt = diaHoraEvt;
       this.tituloMsg = tituloMsg;
    }
   
    public String getTemaEvt() {
        return this.temaEvt;
    }
    
    public void setTemaEvt(String temaEvt) {
        this.temaEvt = temaEvt;
    }
    public Date getDiaHoraEvt() {
        return this.diaHoraEvt;
    }
    
    public void setDiaHoraEvt(Date diaHoraEvt) {
        this.diaHoraEvt = diaHoraEvt;
    }
    public String getTituloMsg() {
        return this.tituloMsg;
    }
    
    public void setTituloMsg(String tituloMsg) {
        this.tituloMsg = tituloMsg;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MinistracaoId) ) return false;
		 MinistracaoId castOther = ( MinistracaoId ) other; 
         
		 return ( (this.getTemaEvt()==castOther.getTemaEvt()) || ( this.getTemaEvt()!=null && castOther.getTemaEvt()!=null && this.getTemaEvt().equals(castOther.getTemaEvt()) ) )
 && ( (this.getDiaHoraEvt()==castOther.getDiaHoraEvt()) || ( this.getDiaHoraEvt()!=null && castOther.getDiaHoraEvt()!=null && this.getDiaHoraEvt().equals(castOther.getDiaHoraEvt()) ) )
 && ( (this.getTituloMsg()==castOther.getTituloMsg()) || ( this.getTituloMsg()!=null && castOther.getTituloMsg()!=null && this.getTituloMsg().equals(castOther.getTituloMsg()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getTemaEvt() == null ? 0 : this.getTemaEvt().hashCode() );
         result = 37 * result + ( getDiaHoraEvt() == null ? 0 : this.getDiaHoraEvt().hashCode() );
         result = 37 * result + ( getTituloMsg() == null ? 0 : this.getTituloMsg().hashCode() );
         return result;
   }   


}


