/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gerenciador.de.igreja;

import CadastroFrames.CadFrameMembro;
import Objetos.*;
import Objetos.Igreja;
import Util.FormatoDataHora;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import CadastroFrames.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Rafael
 */
public final class GerenciadorFrame extends javax.swing.JFrame {

    Igreja igreja;
    private int maxEventos = 20;
    
    /**
     * torna todas os principais paineis invisíveis.
    */
    public void setAllInvisible(){
        jPanelInicio.setVisible(false);
        jPanelDisciplina.setVisible(false);
        jPanelMinisterios.setVisible(false);
        jPanelSecretaria.setVisible(false);
        jPanelGrupo.setVisible(false);
    }
    public GerenciadorFrame(Membro membro) {
        initComponents();
        setAllInvisible(); //tornando todas os paineis principais invisíveis
        jPanelInicio.setVisible(true);
        igreja = new Igreja();
        igreja.setUsuarioAtual(membro);
        refresh();
    }
    
    public void refresh(){
        igreja.carregarEventos(Ordem.DECRESCENTE,maxEventos);
        preencherEventos();
        igreja.carregarNoticias(Ordem.DECRESCENTE);
        preencherNoticias();
        preencherAniversariantes();
        nomeUsuarioAtual.setText(igreja.getUsuarioAtual().getPessoa().getNome());
        dataAtual.setText(FormatoDataHora.userData(FormatoDataHora.getDataHoraAtual()));
        jListOpcaoMenu.setSelectedIndex(0);
        igreja.carregarSeminarios();
        preencherDisciplinasAtivas();
        igreja.carregarMinisterios();
        preencherMinisterios();
        igreja.carregarMensagens();
        preencherMensagens();
        igreja.carregarGrupos();
        preencherQuantidades();
        preencherGrupos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nomeUsuarioAtual = new javax.swing.JLabel();
        dataAtual = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        jPanelInicio = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanelAniversariante = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaAniversariantes = new javax.swing.JTable();
        jPanelNoticias = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaNoticias = new javax.swing.JTable();
        jPanelDiscAtivas = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabelaMensagens = new javax.swing.JTable();
        jPanelEventos = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tabelaEventos = new javax.swing.JTable();
        jToolBar2 = new javax.swing.JToolBar();
        btnNoticia = new javax.swing.JButton();
        btnEvento = new javax.swing.JButton();
        jPanelDisciplina = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tabelaDisciplinasAtivas1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        btnExibirDisciplina = new javax.swing.JButton();
        jPanelMinisterios = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tabelaMinisterios = new javax.swing.JTable();
        btnExibirMinisterio = new javax.swing.JButton();
        btnAdicionarMinisterio = new javax.swing.JButton();
        btnExcluirMinisterio = new javax.swing.JButton();
        jPanelSecretaria = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        btnMembro = new javax.swing.JButton();
        btnVisitante = new javax.swing.JButton();
        btnDisciplina = new javax.swing.JButton();
        btnTurmas = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        lbTotalMembros = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        lbGrupos = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        lbTotalMinisterios = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jPanelGrupo = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        tabelaGrupos = new javax.swing.JTable();
        btnExibirGrupo = new javax.swing.JButton();
        btnAdicionarGrupo = new javax.swing.JButton();
        btnExcluirGrupo = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jListOpcaoMenu = new javax.swing.JList();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Connect Church");

        jPanel1.setAutoscrolls(true);
        jPanel1.setDoubleBuffered(false);
        jPanel1.setInheritsPopupMenu(true);
        jPanel1.setOpaque(false);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setRequestFocusEnabled(false);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Connect Church3.2.png"))); // NOI18N

        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sair.png"))); // NOI18N
        btnLogout.setBorderPainted(false);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Usuário:");

        nomeUsuarioAtual.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        nomeUsuarioAtual.setText("Nome_usuario");

        dataAtual.setText("00/00/0000");

        jLabel13.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 102, 102));
        jLabel13.setText("Data:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dataAtual)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomeUsuarioAtual, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nomeUsuarioAtual))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(dataAtual))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogout))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setMaximumSize(new java.awt.Dimension(849, 533));
        jPanel4.setLayout(null);

        jPanelInicio.setPreferredSize(new java.awt.Dimension(850, 530));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Bem Vindo!");

        jPanelAniversariante.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Aniversariantes do mês", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(96, 155, 125))); // NOI18N

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);

        tabelaAniversariantes.setBackground(new java.awt.Color(196, 255, 225));
        tabelaAniversariantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"João", "10/10"},
                {"Maria", "11/10"},
                {"Emanuel", "20/10"}
            },
            new String [] {
                "NOME", "DATA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaAniversariantes.setGridColor(new java.awt.Color(0, 102, 102));
        tabelaAniversariantes.setSelectionBackground(new java.awt.Color(96, 155, 125));
        tabelaAniversariantes.setShowHorizontalLines(false);
        tabelaAniversariantes.setUpdateSelectionOnSort(false);
        jScrollPane1.setViewportView(tabelaAniversariantes);

        javax.swing.GroupLayout jPanelAniversarianteLayout = new javax.swing.GroupLayout(jPanelAniversariante);
        jPanelAniversariante.setLayout(jPanelAniversarianteLayout);
        jPanelAniversarianteLayout.setHorizontalGroup(
            jPanelAniversarianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
        );
        jPanelAniversarianteLayout.setVerticalGroup(
            jPanelAniversarianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jPanelNoticias.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Notícias", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(101, 155, 106))); // NOI18N

        tabelaNoticias.setBackground(new java.awt.Color(201, 255, 206));
        tabelaNoticias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Os ensaios do grupo \"alguma coisa\" serão cancelados esta semana", "10/10"},
                {null, null},
                {null, null}
            },
            new String [] {
                "ASSUNTO", "DATA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaNoticias.setGridColor(new java.awt.Color(0, 102, 102));
        tabelaNoticias.setSelectionBackground(new java.awt.Color(109, 114, 130));
        tabelaNoticias.setShowHorizontalLines(false);
        tabelaNoticias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaNoticiasMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabelaNoticias);

        javax.swing.GroupLayout jPanelNoticiasLayout = new javax.swing.GroupLayout(jPanelNoticias);
        jPanelNoticias.setLayout(jPanelNoticiasLayout);
        jPanelNoticiasLayout.setHorizontalGroup(
            jPanelNoticiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
        );
        jPanelNoticiasLayout.setVerticalGroup(
            jPanelNoticiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
        );

        jPanelDiscAtivas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Mensagens Ministradas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(109, 114, 130))); // NOI18N

        jScrollPane4.setBorder(null);

        tabelaMensagens.setBackground(new java.awt.Color(209, 214, 230));
        tabelaMensagens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ASSUNTO", "PASSAGEM", "DATA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaMensagens.setGridColor(new java.awt.Color(0, 102, 102));
        tabelaMensagens.setSelectionBackground(new java.awt.Color(101, 155, 106));
        tabelaMensagens.setShowHorizontalLines(false);
        jScrollPane4.setViewportView(tabelaMensagens);

        javax.swing.GroupLayout jPanelDiscAtivasLayout = new javax.swing.GroupLayout(jPanelDiscAtivas);
        jPanelDiscAtivas.setLayout(jPanelDiscAtivasLayout);
        jPanelDiscAtivasLayout.setHorizontalGroup(
            jPanelDiscAtivasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
        );
        jPanelDiscAtivasLayout.setVerticalGroup(
            jPanelDiscAtivasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jPanelEventos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Eventos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(155, 126, 126))); // NOI18N

        tabelaEventos.setBackground(new java.awt.Color(255, 226, 226));
        tabelaEventos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "NOME", "DATA", "HORA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaEventos.setGridColor(new java.awt.Color(0, 102, 102));
        tabelaEventos.setSelectionBackground(new java.awt.Color(155, 126, 126));
        tabelaEventos.setShowHorizontalLines(false);
        tabelaEventos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaEventosMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tabelaEventos);

        javax.swing.GroupLayout jPanelEventosLayout = new javax.swing.GroupLayout(jPanelEventos);
        jPanelEventos.setLayout(jPanelEventosLayout);
        jPanelEventosLayout.setHorizontalGroup(
            jPanelEventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanelEventosLayout.setVerticalGroup(
            jPanelEventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
        );

        jToolBar2.setBorder(null);
        jToolBar2.setFloatable(false);
        jToolBar2.setRollover(true);

        btnNoticia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/noticia.png"))); // NOI18N
        btnNoticia.setFocusable(false);
        btnNoticia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNoticia.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNoticia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoticiaActionPerformed(evt);
            }
        });
        jToolBar2.add(btnNoticia);

        btnEvento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cEvento.png"))); // NOI18N
        btnEvento.setFocusable(false);
        btnEvento.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEvento.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEventoActionPerformed(evt);
            }
        });
        jToolBar2.add(btnEvento);

        javax.swing.GroupLayout jPanelInicioLayout = new javax.swing.GroupLayout(jPanelInicio);
        jPanelInicio.setLayout(jPanelInicioLayout);
        jPanelInicioLayout.setHorizontalGroup(
            jPanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInicioLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanelInicioLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInicioLayout.createSequentialGroup()
                        .addComponent(jPanelAniversariante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelNoticias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelInicioLayout.createSequentialGroup()
                        .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelInicioLayout.createSequentialGroup()
                        .addComponent(jPanelDiscAtivas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelEventos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelInicioLayout.setVerticalGroup(
            jPanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInicioLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(jPanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelNoticias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelAniversariante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(7, 7, 7)
                .addGroup(jPanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelEventos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelDiscAtivas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel4.add(jPanelInicio);
        jPanelInicio.setBounds(0, 0, 850, 530);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Disciplinas Ativas"));

        jScrollPane6.setBorder(null);

        tabelaDisciplinasAtivas1.setBackground(new java.awt.Color(201, 255, 206));
        tabelaDisciplinasAtivas1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Aprender a ser Gente", "15/06/0000", "10/11/0000"},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "NOME", "INÍCIO", "TÉRMINO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaDisciplinasAtivas1.setGridColor(new java.awt.Color(0, 102, 102));
        tabelaDisciplinasAtivas1.setSelectionBackground(new java.awt.Color(101, 155, 106));
        tabelaDisciplinasAtivas1.setShowHorizontalLines(false);
        jScrollPane6.setViewportView(tabelaDisciplinasAtivas1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Disciplinas do Período Letivo");

        btnExibirDisciplina.setBackground(new java.awt.Color(204, 255, 204));
        btnExibirDisciplina.setText("Exibir");
        btnExibirDisciplina.setFocusable(false);
        btnExibirDisciplina.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExibirDisciplina.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExibirDisciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExibirDisciplinaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDisciplinaLayout = new javax.swing.GroupLayout(jPanelDisciplina);
        jPanelDisciplina.setLayout(jPanelDisciplinaLayout);
        jPanelDisciplinaLayout.setHorizontalGroup(
            jPanelDisciplinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDisciplinaLayout.createSequentialGroup()
                .addContainerGap(87, Short.MAX_VALUE)
                .addGroup(jPanelDisciplinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExibirDisciplina, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(96, 96, 96))
        );
        jPanelDisciplinaLayout.setVerticalGroup(
            jPanelDisciplinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDisciplinaLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel5)
                .addGap(64, 64, 64)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExibirDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        jPanel4.add(jPanelDisciplina);
        jPanelDisciplina.setBounds(0, 0, 850, 540);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 102, 102));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Ministérios");

        tabelaMinisterios.setBackground(new java.awt.Color(255, 204, 204));
        tabelaMinisterios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Louvor", "Marcos", "seg/quar", "18:30 - 21:00"}
            },
            new String [] {
                "NOME", "LÍDER", "DIA", "HORA"
            }
        ));
        jScrollPane7.setViewportView(tabelaMinisterios);

        btnExibirMinisterio.setBackground(new java.awt.Color(204, 255, 204));
        btnExibirMinisterio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/visualizar.png"))); // NOI18N
        btnExibirMinisterio.setText("Exibir");
        btnExibirMinisterio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExibirMinisterioActionPerformed(evt);
            }
        });

        btnAdicionarMinisterio.setBackground(new java.awt.Color(204, 204, 255));
        btnAdicionarMinisterio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        btnAdicionarMinisterio.setText("Adicionar");
        btnAdicionarMinisterio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarMinisterioActionPerformed(evt);
            }
        });

        btnExcluirMinisterio.setBackground(new java.awt.Color(255, 204, 204));
        btnExcluirMinisterio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/deletar.png"))); // NOI18N
        btnExcluirMinisterio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirMinisterioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMinisteriosLayout = new javax.swing.GroupLayout(jPanelMinisterios);
        jPanelMinisterios.setLayout(jPanelMinisteriosLayout);
        jPanelMinisteriosLayout.setHorizontalGroup(
            jPanelMinisteriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE)
            .addGroup(jPanelMinisteriosLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(jPanelMinisteriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelMinisteriosLayout.createSequentialGroup()
                        .addComponent(btnExcluirMinisterio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAdicionarMinisterio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExibirMinisterio, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelMinisteriosLayout.setVerticalGroup(
            jPanelMinisteriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMinisteriosLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelMinisteriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAdicionarMinisterio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExibirMinisterio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExcluirMinisterio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39))
        );

        jPanel4.add(jPanelMinisterios);
        jPanelMinisterios.setBounds(0, 0, 850, 530);

        jPanelSecretaria.setPreferredSize(new java.awt.Dimension(849, 533));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 102, 102));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Administração e Secretaria");

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opções", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 102, 102))); // NOI18N
        jPanel9.setOpaque(false);
        jPanel9.setLayout(new javax.swing.BoxLayout(jPanel9, javax.swing.BoxLayout.LINE_AXIS));

        btnMembro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CMembro.png"))); // NOI18N
        btnMembro.setToolTipText("");
        btnMembro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMembroActionPerformed(evt);
            }
        });
        jPanel9.add(btnMembro);

        btnVisitante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CVisitante.png"))); // NOI18N
        btnVisitante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVisitanteMouseClicked(evt);
            }
        });
        jPanel9.add(btnVisitante);

        btnDisciplina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CDisciplina.png"))); // NOI18N
        btnDisciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisciplinaActionPerformed(evt);
            }
        });
        jPanel9.add(btnDisciplina);

        btnTurmas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Turmas.png"))); // NOI18N
        btnTurmas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTurmasActionPerformed(evt);
            }
        });
        jPanel9.add(btnTurmas);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Membros", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        lbTotalMembros.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        lbTotalMembros.setForeground(new java.awt.Color(0, 102, 102));
        lbTotalMembros.setText("50");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(lbTotalMembros)
                .addContainerGap(74, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lbTotalMembros)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Grupos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        lbGrupos.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        lbGrupos.setForeground(new java.awt.Color(0, 102, 102));
        lbGrupos.setText("2");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(lbGrupos)
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lbGrupos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ministérios", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        lbTotalMinisterios.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        lbTotalMinisterios.setForeground(new java.awt.Color(0, 102, 102));
        lbTotalMinisterios.setText("6");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addComponent(lbTotalMinisterios)
                .addGap(62, 62, 62))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbTotalMinisterios)
                .addGap(21, 21, 21))
        );

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel6.setText("Balanço Total:");

        javax.swing.GroupLayout jPanelSecretariaLayout = new javax.swing.GroupLayout(jPanelSecretaria);
        jPanelSecretaria.setLayout(jPanelSecretariaLayout);
        jPanelSecretariaLayout.setHorizontalGroup(
            jPanelSecretariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 849, Short.MAX_VALUE)
            .addGroup(jPanelSecretariaLayout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1))
            .addGroup(jPanelSecretariaLayout.createSequentialGroup()
                .addGroup(jPanelSecretariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSecretariaLayout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelSecretariaLayout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelSecretariaLayout.setVerticalGroup(
            jPanelSecretariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSecretariaLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel17)
                .addGap(81, 81, 81)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE)
                .addGroup(jPanelSecretariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelSecretariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel4.add(jPanelSecretaria);
        jPanelSecretaria.setBounds(0, 0, 850, 530);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 102, 102));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Grupos");

        tabelaGrupos.setBackground(new java.awt.Color(209, 214, 230));
        tabelaGrupos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Louvor", "Marcos", "seg/quar", "18:30 - 21:00"}
            },
            new String [] {
                "TIPO", "LÍDER", "DIA", "HORA"
            }
        ));
        jScrollPane9.setViewportView(tabelaGrupos);

        btnExibirGrupo.setBackground(new java.awt.Color(204, 255, 204));
        btnExibirGrupo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/visualizar.png"))); // NOI18N
        btnExibirGrupo.setText("Exibir");
        btnExibirGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExibirGrupoActionPerformed(evt);
            }
        });

        btnAdicionarGrupo.setBackground(new java.awt.Color(204, 204, 255));
        btnAdicionarGrupo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        btnAdicionarGrupo.setText("Adicionar");
        btnAdicionarGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarGrupoActionPerformed(evt);
            }
        });

        btnExcluirGrupo.setBackground(new java.awt.Color(255, 204, 204));
        btnExcluirGrupo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/deletar.png"))); // NOI18N
        btnExcluirGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirGrupoGrupoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelGrupoLayout = new javax.swing.GroupLayout(jPanelGrupo);
        jPanelGrupo.setLayout(jPanelGrupoLayout);
        jPanelGrupoLayout.setHorizontalGroup(
            jPanelGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE)
            .addGroup(jPanelGrupoLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(jPanelGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelGrupoLayout.createSequentialGroup()
                        .addComponent(btnExcluirGrupo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAdicionarGrupo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExibirGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelGrupoLayout.setVerticalGroup(
            jPanelGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGrupoLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAdicionarGrupo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExibirGrupo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExcluirGrupo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39))
        );

        jPanel4.add(jPanelGrupo);
        jPanelGrupo.setBounds(0, 0, 850, 530);

        jScrollPane2.setViewportView(jPanel4);

        jPanel5.setBackground(new java.awt.Color(0, 102, 102));

        jListOpcaoMenu.setBackground(new java.awt.Color(0, 102, 102));
        jListOpcaoMenu.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jListOpcaoMenu.setForeground(new java.awt.Color(255, 255, 255));
        jListOpcaoMenu.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "   Início   ", "   Disciplinas   ", "   Grupos    ", "   Ministérios   ", "   Secretaria   " };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jListOpcaoMenu.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListOpcaoMenu.setAutoscrolls(false);
        jListOpcaoMenu.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jListOpcaoMenu.setDropMode(javax.swing.DropMode.INSERT);
        jListOpcaoMenu.setFocusable(false);
        jListOpcaoMenu.setInheritsPopupMenu(true);
        jListOpcaoMenu.setLayoutOrientation(javax.swing.JList.HORIZONTAL_WRAP);
        jListOpcaoMenu.setRequestFocusEnabled(false);
        jListOpcaoMenu.setVerifyInputWhenFocusTarget(false);
        jListOpcaoMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListOpcaoMenuMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jListOpcaoMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jListOpcaoMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(441, 441, 441))
        );

        jListOpcaoMenu.getAccessibleContext().setAccessibleName("");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ITB.png"))); // NOI18N
        jLabel4.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(2, 2, 2))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addGap(2, 2, 2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 834, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addGap(1, 1, 1)
                        .addComponent(jLabel4))))
        );

        jMenu1.setText("Alunos");

        jMenuItem1.setText("cadastrar");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("remover");
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("ver notas");
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Eventos");

        jMenuItem4.setText("cadastrar");
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jListOpcaoMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListOpcaoMenuMouseClicked
        // TODO add your handling code here:
        String opcao = jListOpcaoMenu.getSelectedValue().toString().replace(" ", "");
        setAllInvisible();
        if(opcao.equals("Início")){
            jPanelInicio.setVisible(true);
        } else if(opcao.equals("Disciplinas")){
            jPanelDisciplina.setVisible(true);
        } else if(opcao.equals("Ministérios")){
            jPanelMinisterios.setVisible(true);
        } else if(opcao.equals("Secretaria")){
            jPanelSecretaria.setVisible(true);
        } else if(opcao.equals("Grupos")){
            jPanelGrupo.setVisible(true);
        }
    }//GEN-LAST:event_jListOpcaoMenuMouseClicked

    private void btnExibirDisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExibirDisciplinaActionPerformed
        // TODO add your handling code here:
        FrameTurmas framedisciplinas = new FrameTurmas();
        framedisciplinas.setVisible(true);
    }//GEN-LAST:event_btnExibirDisciplinaActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        try {
            TelaLogin login = new TelaLogin();
            login.setVisible(true);
            this.dispose();
        } catch (Throwable ex) {
            Logger.getLogger(GerenciadorFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnNoticiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoticiaActionPerformed
            CadFrameNoticia cadnoticia = new CadFrameNoticia(this,igreja.getUsuarioAtual());
            cadnoticia.setVisible(true);
            refresh();

    }//GEN-LAST:event_btnNoticiaActionPerformed

    private void btnEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEventoActionPerformed
        CadFrameEvento cadframeevento = new CadFrameEvento(this);
        cadframeevento.setVisible(true);
    }//GEN-LAST:event_btnEventoActionPerformed

    private void btnMembroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMembroActionPerformed
        CadFrameMembro cadmembro = new CadFrameMembro(this);
        cadmembro.setVisible(true);
    }//GEN-LAST:event_btnMembroActionPerformed

    private void btnVisitanteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVisitanteMouseClicked
        CadFrameVisitante cadvisitante = new CadFrameVisitante(this);
        cadvisitante.setVisible(true);
    }//GEN-LAST:event_btnVisitanteMouseClicked

    private void btnAdicionarGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarGrupoActionPerformed
        CadFrameGrupo cadgrupo = new CadFrameGrupo(this);
        cadgrupo.setVisible(true);
    }//GEN-LAST:event_btnAdicionarGrupoActionPerformed

    private void btnTurmasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTurmasActionPerformed
        CadFrameTurma frameturmas = new CadFrameTurma();
        frameturmas.setVisible(true);
    }//GEN-LAST:event_btnTurmasActionPerformed

    private void btnAdicionarMinisterioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarMinisterioActionPerformed
        CadFrameMinisterio cadministerio = new CadFrameMinisterio(this);
        cadministerio.setVisible(true);
    }//GEN-LAST:event_btnAdicionarMinisterioActionPerformed

    private void btnExibirGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExibirGrupoActionPerformed
        int index = tabelaGrupos.getSelectedRow();
        if (index == -1){
            JOptionPane.showMessageDialog(null, "Selecione um grupo para exibir");
            return;
        }
        FrameGrupo framegrupos = new FrameGrupo(this,igreja.getGrupos().get(index));
        framegrupos.setVisible(true);
    }//GEN-LAST:event_btnExibirGrupoActionPerformed

    private void btnExibirMinisterioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExibirMinisterioActionPerformed
        int index = tabelaMinisterios.getSelectedRow();
        if (index == -1){
            JOptionPane.showMessageDialog(null, "Selecione o ministério para exibir");
            return;
        }
        FrameMinisterio frameministerio = new FrameMinisterio(igreja.getMinisterios().get(index),this);
        frameministerio.setVisible(true);
    }//GEN-LAST:event_btnExibirMinisterioActionPerformed

    private void btnDisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisciplinaActionPerformed
        CadFrameDisciplina cadframedisciplinas = new CadFrameDisciplina(this);
        cadframedisciplinas.setVisible(true);
    }//GEN-LAST:event_btnDisciplinaActionPerformed

    private void tabelaNoticiasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaNoticiasMouseClicked
        if (evt.getClickCount() == 2){
            int index = tabelaNoticias.getSelectedRow();
            Noticia noticia = igreja.getNoticias().get(index);
            CadFrameNoticia frameNoticia = new CadFrameNoticia(this, igreja.getUsuarioAtual(),noticia);
            frameNoticia.setVisible(true);
        }
    }//GEN-LAST:event_tabelaNoticiasMouseClicked

    private void tabelaEventosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaEventosMouseClicked
        if (evt.getClickCount() == 2){
            int index = tabelaEventos.getSelectedRow();
            Evento eventoSelecionado = igreja.getEventos().get(index);
            CadFrameEvento cadframeevento = new CadFrameEvento(this,eventoSelecionado);
            cadframeevento.setVisible(true);
        }
    }//GEN-LAST:event_tabelaEventosMouseClicked

    private void btnExcluirGrupoGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirGrupoGrupoActionPerformed
        int index = tabelaGrupos.getSelectedRow();
        if (index == -1){
            JOptionPane.showMessageDialog(null, "Selecione um grupo para excluir");
            return;
        }
        int confirm = JOptionPane.showConfirmDialog(null,"Tem certeza de que deseja excluir o grupo?","", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION){
            return;
        }
        try{
            Grupo.deletarGrupo(igreja.getGrupos().get(index));
            refresh();
            JOptionPane.showMessageDialog(null, "Grupo excluído");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e.toString());
        }
    }//GEN-LAST:event_btnExcluirGrupoGrupoActionPerformed

    private void btnExcluirMinisterioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirMinisterioActionPerformed
        int index = tabelaMinisterios.getSelectedRow();
        if (index == -1){
            JOptionPane.showMessageDialog(null, "Selecione um ministério para excluir");
            return;
        }
        int confirm = JOptionPane.showConfirmDialog(null,"Tem certeza de que deseja excluir o ministério?","", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION){
            return;
        }
        try{
            Ministerio.deletarMinisterio(igreja.getMinisterios().get(index));
            refresh();
            JOptionPane.showMessageDialog(null, "Ministério excluído");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }//GEN-LAST:event_btnExcluirMinisterioActionPerformed

    private void preencherEventos(){
        DefaultTableModel model = (DefaultTableModel) tabelaEventos.getModel();
        model.setNumRows(0);
        List<Evento> eventos = igreja.getEventos();
        Object[] objs = new Object[3];
        for (Evento evento : eventos){
            objs[0] = evento.getId().getTema();
            objs[1] = FormatoDataHora.userData(evento.getId().getDiaHora());
            objs[2] = FormatoDataHora.userHora(evento.getId().getDiaHora());
           
            model.addRow(objs);
        }
    }
    
    private void preencherNoticias(){
        DefaultTableModel model = (DefaultTableModel) tabelaNoticias.getModel();
        model.setNumRows(0);
        List<Noticia> noticias = igreja.getNoticias();
        Object[] objs = new Object[2];
        for (Noticia not : noticias) {
            objs[0] = not.getManchete();
            objs[1] = FormatoDataHora.userData(not.getData());
            
            model.addRow(objs);
        }
    }
    
    private void preencherAniversariantes(){
        DefaultTableModel model = (DefaultTableModel) tabelaAniversariantes.getModel();
        model.setNumRows(0);
        List<Membro> aniversariantes = Membro.selectAniversariantesDoMes(Ordem.CRESCENTE);
        Object[] objs = new Object[2];
        for (Membro membro : aniversariantes){
            objs[0] = membro.getPessoa().getNome();
            objs[1] = FormatoDataHora.userDataDiaMes(membro.getDataNasc());
            model.addRow(objs);
        }
    }
    
    private void preencherDisciplinasAtivas() {
        DefaultTableModel model = (DefaultTableModel) tabelaDisciplinasAtivas1.getModel();
        model.setNumRows(0);
        //get(0) pelo fato de por padrão só existir um seminário
        List<Turma> disciplinasAtivas = igreja.getSeminarios().get(0).selectDisciplinasAtivas();
        Object[] objs = new Object[3];
        for (Turma turma : disciplinasAtivas){
            objs[0] = turma.getDisciplina().getNome();
            objs[1] = FormatoDataHora.userData(turma.getId().getDataInicio());
            objs[2] = FormatoDataHora.userData(turma.getDataFim());
            model.addRow(objs);
        }
    }
    
    private void preencherMensagens(){
        DefaultTableModel model = (DefaultTableModel) tabelaMensagens.getModel();
        model.setNumRows(0);
        List<Ministracao> ministracoes = Ministracao.listarTodos();
        Object[] objs = new Object[3];
        for (Ministracao ministracao: ministracoes){
            objs[0] = ministracao.getMensagem().getTitulo();
            objs[1] = ministracao.getMensagem().getBaseBiblica();
            objs[2] = FormatoDataHora.userData(ministracao.getEvento().getId().getDiaHora());
            model.addRow(objs);
        }
    }
    
    private void preencherMinisterios(){
        DefaultTableModel model = (DefaultTableModel) tabelaMinisterios.getModel();
        model.setNumRows(0);
        Object[] objs = new Object[4];
        for (Ministerio ministerio : igreja.getMinisterios()) {
            objs[0] = ministerio.getNome();
            objs[1] = ministerio.getLider().getPessoa().getNome();
            objs[2] = ministerio.getDiaSemana();
            objs[3] = FormatoDataHora.userHora(ministerio.getHora());
            model.addRow(objs);
        }
    }
    
    private void preencherGrupos(){
        DefaultTableModel model = (DefaultTableModel) tabelaGrupos.getModel();
        model.setNumRows(0);
        Object[] objs = new Object[4];
        for (Grupo grupo : igreja.getGrupos()) {
            objs[0] = grupo.getTipoGrupo();
            objs[1] = grupo.getLider().getPessoa().getNome();
            objs[2] = grupo.getId().getDiaSemana();
            objs[3] = FormatoDataHora.userHora(grupo.getId().getHora());
            model.addRow(objs);
        }
    }
    
    private void preencherQuantidades(){
        lbTotalMembros.setText(Integer.toString(Membro.getNumeroDeMembros()));
        lbTotalMinisterios.setText(Integer.toString(Ministerio.getNumeroMinisterios()));
        lbGrupos.setText(Integer.toString(Grupo.getNumeroDeGrupos()));
    }
    
    public Igreja getIgreja(){
        return igreja;
    }  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarGrupo;
    private javax.swing.JButton btnAdicionarMinisterio;
    private javax.swing.JButton btnDisciplina;
    private javax.swing.JButton btnEvento;
    private javax.swing.JButton btnExcluirGrupo;
    private javax.swing.JButton btnExcluirMinisterio;
    private javax.swing.JButton btnExibirDisciplina;
    private javax.swing.JButton btnExibirGrupo;
    private javax.swing.JButton btnExibirMinisterio;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnMembro;
    private javax.swing.JButton btnNoticia;
    private javax.swing.JButton btnTurmas;
    private javax.swing.JButton btnVisitante;
    private javax.swing.JLabel dataAtual;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList jListOpcaoMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelAniversariante;
    private javax.swing.JPanel jPanelDiscAtivas;
    private javax.swing.JPanel jPanelDisciplina;
    private javax.swing.JPanel jPanelEventos;
    private javax.swing.JPanel jPanelGrupo;
    private javax.swing.JPanel jPanelInicio;
    private javax.swing.JPanel jPanelMinisterios;
    private javax.swing.JPanel jPanelNoticias;
    private javax.swing.JPanel jPanelSecretaria;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JLabel lbGrupos;
    private javax.swing.JLabel lbTotalMembros;
    private javax.swing.JLabel lbTotalMinisterios;
    private javax.swing.JLabel nomeUsuarioAtual;
    private javax.swing.JTable tabelaAniversariantes;
    private javax.swing.JTable tabelaDisciplinasAtivas1;
    private javax.swing.JTable tabelaEventos;
    private javax.swing.JTable tabelaGrupos;
    private javax.swing.JTable tabelaMensagens;
    private javax.swing.JTable tabelaMinisterios;
    private javax.swing.JTable tabelaNoticias;
    // End of variables declaration//GEN-END:variables

    
}
